### ISSUE TITLE
roadmap to 1.0

### ISSUE THREAD

**Issue by chadwhitacre** [AspenWeb/pando.py#357]
# ~~[Target](https://github.com/AspenWeb/pando.py/issues/357#issuecomment-181915970): September 19, 2016 👍~~

1.0:
- [x] port to Windows (#443)
- [x] rationalize dispatch (#366)
- [x] switch back to stdlib logging (#157)
- [x] port to aspen.py (#548)
- [x] port to Python 3 (#493)
- [x] simplify configuration (~~#373~~, ~~#374~~, ~~#444~~, ~~#473~~)
- [x] fix some bugs/issues
  - [x] https://github.com/AspenWeb/pando.py/issues/429
  - [x] https://github.com/AspenWeb/aspen.py/issues/24
  - [x] https://github.com/AspenWeb/aspen.py/issues/12
  - [ ] https://github.com/AspenWeb/aspen.py/issues/22
- [x] mothball the other language versions—https://github.com/AspenWeb/pando.py/issues/357#issuecomment-245383148
- [x] stub out RtD sites—https://github.com/AspenWeb/pando.py/issues/357#issuecomment-245401913
  - [x] Aspen
  - [x] django-aspen
  - [x] Flask-Aspen
  - [x] Pando
- [ ] publish docs on RtD
  - [x] Aspen
  - [ ] django-aspen
  - [ ] Flask-Aspen
  - [x] Pando (#339)
- [ ] release 1.0 versions
  - [ ] Aspen
  - [ ] django-aspen
  - [ ] Flask-Aspen
  - [ ] Pando
- [ ] dust off editor plugins
  - [ ] simplate.vim
  - [ ] simplates.emacs
- [ ] sort out Aspen plugins
- [ ] publish the new http://aspen.io/ (https://github.com/AspenWeb/aspen.io/issues/2)
- [ ] redirect http://simplates.org/ to http://aspen.io/

Post-1.0:
- [ ] flatten algorithm further (unroll deep calls) (#423)
- [ ] calve off simplates (#341), this would take renderers with it

Also relevant:
- [ ] find or make a library library (https://github.com/gratipay/inside.gratipay.com/issues/309)

**Comment by whit537** [comment]
Yay @pjz for porting to Windows in #443! :dancer:

**Comment by whit537** [comment]
Yay @pjz for refactoring simplates into a submodule in #481, paving the way for #341! :D

**Comment by whit537** [comment]
Decided on #537 (oooh! 537 get! :dancer:) to aim for a 1.0 release on September 19, since that is [10 years to the day](https://github.com/gratipay/aspen.py/issues/526#issuecomment-155439243) from the first commit on the Aspen repo.

**Comment by whit537** [comment]
In light of recent events, I've subbed the following in the description:

> - [ ] drop Request/Response objects (#526)

for

> - [ ] port to aspen-core.py

**Comment by whit537** [comment]
https://github.com/AspenWeb/aspen.io/issues/1#issuecomment-234088604

> How about a 0.90 release for Aspen in the next few weeks, and 1.0 in September?

My tendency would be to stick with our current `0.n+1` versioning scheme until `1.0.0`.

**Comment by whit537** [comment]
> Yes, python3 is the next item in my TODO. Don't know when I'll get around to it, but it should be doable before 1.0.

Awesome! Besides that, the other major piece of coding to be completed is #548, which you've got underway in #556.

As [discussed](https://github.com/AspenWeb/aspen.io/issues/1#issuecomment-234076992), I'll commit to https://github.com/AspenWeb/aspen.io/issues/1 (I've added it to the roadmap). I'm also happy to take #339, which could surface some API cleanups along the way.

**Comment by whit537** [comment]
@Changaco Should we drop #473 from 1.0?

**Comment by Changaco** [comment]
I don't know, but I don't see #473 as a blocker for 1.0 if that's what you're asking.

**Comment by whit537** [comment]
Yeah, that's what I'm asking.

**Comment by Changaco** [comment]
I've just noticed that there was [an old 1.0 milestone](https://github.com/AspenWeb/pando.py/milestone/1), so I've closed it.

**Comment by Changaco** [comment]
And the [Simplify Simplates](https://github.com/AspenWeb/pando.py/milestone/3) milestone too.

**Comment by whit537** [comment]
> I've closed it.

Eep! Does that mean we've reached 1.0?! 😳

**Comment by Changaco** [comment]
Nope, especially since it still had an open issue. I closed the milestone because it was out-of-date since you've been using this issue for the 1.0 roadmap instead.

**Comment by whit537** [comment]
Commandeering this ticket to drive Pando 1.0 (so it's clear when we can close it ;).

**Comment by whit537** [comment]
@Changaco Thanks for all the awesome work lately moving us towards 1.0. Now that I've made it through the [Abstractions](https://github.com/gratipay/inside.gratipay.com/issues/534) conference, I'm going to try to get Team Gratipay [payouts](https://github.com/gratipay/gratipay.com/issues/3994) done ASAP, so that I can buckle down in September to do my part in getting us to Pando.

**Comment by whit537** [comment]
Alright @Changaco, I'm here! Well, almost ... I have to do paid work today and Monday 😁 , but I intend to spend my unpaid work time through September 19 getting Pando 1.0 out the door! Let's do it! 💃

**Comment by Changaco** [comment]
I'm ready. ;-) I also have some contract work, but the job is almost finished, and it didn't prevent me from working on Aspen in August anyway.

**Comment by whit537** [comment]
Eeeeeeeee! We could get `pando.wf`. 😁

**Comment by whit537** [comment]
I've staked out [Pando on PyPI](https://pypi.python.org/pypi/pando) and added you as an owner, @Changaco.

**Comment by whit537** [comment]
Ditto [django-aspen](https://pypi.python.org/pypi/django-aspen) and [Flask-Aspen](https://pypi.python.org/pypi/Flask-Aspen) (though I don't expect you to care much about those ;).

**Comment by whit537** [comment]
@Changaco I've updated the task list in the ticket description here.

**Comment by Changaco** [comment]
@whit537 Have you looked at the [open aspen.py issues](https://github.com/AspenWeb/aspen.py/issues)? Is there any you'd like to see closed before 1.0?

**Comment by whit537** [comment]
@Changaco Looking at the four issues, it seems that https://github.com/AspenWeb/aspen.py/issues/24 and https://github.com/AspenWeb/aspen.py/issues/12 would be good to get done before 1.0, to avoid having to maintain backwards-compatibility. https://github.com/AspenWeb/aspen.py/issues/23 shouldn't be a problem to add later. https://github.com/AspenWeb/aspen.py/issues/22 should get done, but I expect that to come out in the wash when I start working in earnest on Aspen's docs.

**Comment by whit537** [comment]
Picking up from https://github.com/AspenWeb/aspen.io/issues/1#issuecomment-245222332 ...

> I suggest doing nothing other than changing the repo descriptions.

I renamed the repos:

https://github.com/AspenWeb/experimental-go-version
https://github.com/AspenWeb/experimental-javascript-version
https://github.com/AspenWeb/experimental-ruby-version

And I modified their description:

> Experimental {} version of Aspen/Pando. Want it? :) http://aspen.io/

**Comment by whit537** [comment]
I'm working on configuring RtD for our several projects.

@Changaco Should we use subdomains of `readthedocs.io` or of `aspen.io` for project docs?

http://pando.aspen.io/
http://flask.aspen.io/
http://django.aspen.io/
http://core.aspen.io/
http://algorithm.aspen.io/
http://filesystem_tree.aspen.io/
http://dependency_injection.aspen.io/

... or ...

http://pando.readthedocs.io/
http://flask-aspen.readthedocs.io/
http://django-aspen.readthedocs.io/
http://aspen.readthedocs.io/
http://algorithm.readthedocs.io/ (already taken)
http://filesystem-tree.readthedocs.io/
http://dependency-injection.readthedocs.io/

For the last three we currently use:

http://algorithm-py.readthedocs.io/
http://filesystem-tree-py.readthedocs.io/
http://dependency-injection-py.readthedocs.io/

This suggests either that the others would also have `-py` in the domain, or that we would use `aspen.io` to avoid namespace collisions. Or we could leave those three as-is since they're lower-level libraries that don't really have anything to do with Aspen _per se_, and use either of these sets for the other four:

http://pando.aspen.io/
http://flask.aspen.io/
http://django.aspen.io/
http://core.aspen.io/

or under RtD, with or without the `-py`:

http://pando.readthedocs.io/
http://flask-aspen.readthedocs.io/
http://django-aspen.readthedocs.io/
http://aspen.readthedocs.io/

Do you care?

**Comment by whit537** [comment]
I'm leaning towards leaving the three lower-level libraries as-is, and using `aspen.io` for aspen.py and above:

http://pando.aspen.io/
http://flask.aspen.io/
http://django.aspen.io/
http://core.aspen.io/

**Comment by Changaco** [comment]
I don't really have a preference.

**Comment by whit537** [comment]
Okay, proceeding with subdomains of `aspen.io` for the four new doc sites, leaving the other three alone.

**Comment by whit537** [comment]
http://django.aspen.io/
http://django.aspen.io/
http://flask.aspen.io/
http://django.aspen.io/

**Comment by whit537** [comment]
Okay! I've stubbed out four new RtD projects:

http://core.aspen.io/
http://django.aspen.io/
http://flask.aspen.io/
http://pando.aspen.io/

**Comment by Changaco** [comment]
If we have enough time we should try to take care of #222 before 1.0.

**Comment by whit537** [comment]
@Changaco FYI I'm working top down from https://github.com/AspenWeb/aspen.io/issues/1. Once the [homepage](http://new.aspen.io/) looks good enough, I'll start working through the links away from it:

- framework libraries
- aspen plugins
- editor plugins

Making each of those linked pages say what we want them to say will fan out into code changes. Basically, however far we get in the next week is what I expect we'll declare 1.0.

**Comment by Changaco** [comment]
I'm going to release Aspen 1.0rc2 and Pando 0.44, then see if Liberapay can run on top of those in production.

**Comment by Changaco** [comment]
/o\ I forgot to adapt Pando's code to AspenWeb/aspen.py#31: https://travis-ci.org/AspenWeb/pando.py/builds/158823441

**Comment by Changaco** [comment]
Okay, second Liberapay PR is <https://github.com/liberapay/liberapay.com/pull/408>. I'm going to sleep now, I'll probably deploy tomorrow.

**Comment by Changaco** [comment]
https://liberapay.com/ is now running on Pando 0.44 and Aspen 1.0rc1. \o/

**Comment by whit537** [comment]
Alright, my moderated goal at this point is to release Aspen 1.0 next Monday, with Pando 1.0 to follow sometime after that. Flask-Aspen and django-aspen will also have to wait, along with the new aspen.io website. The old aspen.io site still points to Aspen 0.42, and I think we can leave it that way until all the pieces are in place. I think that's a more realistic goal, given what I can dedicate to this this week.

Can you live with that, @Changaco?

**Comment by Changaco** [comment]
I think we really need a new aspen.io, the old one is obsolete. I don't think the flask and django plugins have to be ready for production in order to push the new aspen.io, we can refer to them as WIP and put pando on top for now.

It seems like a big share of the remaining work is documentation, and so far you've been doing it alone, but if you delegate some of it to me then we should be able to do more.

**Comment by whit537** [comment]
How about doing https://github.com/AspenWeb/aspen.py/pull/32 for Pando? Right now http://pando.aspen.io/ is empty. Surfacing all of the existing module reference documentation seems like the first step in writing the documentation for Pando.

**Comment by Changaco** [comment]
Okay, I'm on it.

**Comment by whit537** [comment]
Sorry we didn't make the September 19 target, @Changaco. 😞

**Comment by Changaco** [comment]
That's fine, we've still made good progress. :-)
